services:
  cockroach:
    image: cockroachdb/cockroach:latest-v24.3
    command: start-single-node --insecure --http-addr=0.0.0.0:8080
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - crdb_data:/cockroach/cockroach-data

volumes:
  crdb_data:
